### PR TITLE
Handler

### PR DESCRIPTION
**Pull request by nicket97**
i know it is not working but it seems to be a problem in the A_STAR throwing an exception and reacting with out of bounds on a valid mission

Out of bounds
Out of bounds
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at robot.A_Star.findRoute(A_Star.java:70)
	at robot.RobotHandler.task(RobotHandler.java:77)
	at robot.RobotHandler.executeMission(RobotHandler.java:42)
	at controller.RobotController.executeMission(RobotController.java:125)
	at controller.MissionEditor.lambda$initialize$5(MissionEditor.java:99)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)

### CODE REVIEW

**Comment by nicket97** [comment]
Where should I call that?

**Comment by Anthony1911** [comment]
I added it already, it should be called right after Hospital is created.

**Comment by nicket97** [comment]
should we merge?

**Comment by Anthony1911** [comment]
Not yet, it hangs when mission is selected for some reason.

**Comment by nicket97** [comment]
i will look in to that :)

**Comment by Anthony1911** [comment]
Can you also go online on Slack if possible?

**Pull request merged**
